name: 🧪 Test Nodes Only

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: '测试模式'
        required: false
        default: 'full'
        type: choice
        options:
          - basic
          - speed
          - full

env:
  TZ: 'Asia/Shanghai'

jobs:
  test-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Tools
        run: |
          pip install requests PyYAML aiohttp
          sudo apt-get update
          sudo apt-get install -y curl wget netcat-openbsd

      - name: Download Raw Nodes
        uses: actions/download-artifact@v3
        with:
          name: raw-nodes

      - name: Run Node Tests
        env:
          TEST_MODE: ${{ github.event.inputs.test_mode }}
        run: |
          python3 scripts/test_nodes.py

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.json
